name: Android APK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer & p4a
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.local/share/python-for-android
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev curl unzip git

      - name: Download Haar Cascade
        run: |
          mkdir -p data
          curl -sSfL \
            https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml \
            -o data/haarcascade_frontalface_default.xml

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install pip requirements
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK (debug)
        run: |
          buildozer --verbose android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: FaceApp-debug.apk
          path: bin/*.apk
